name: ${IMAGE_NAME:-quickvulkanv1}

services:
  quickvulkanv1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Vulkan SDK selection
        USE_DISTRO_VULKAN: "${USE_DISTRO_VULKAN:-false}"
        VULKAN_SDK_VERSION: "${VULKAN_SDK_VERSION:-1.3.296.0}"

        # Android toolchain selection
        ANDROID_SDK_VERSION:  "${ANDROID_SDK_VERSION:-11076708_latest}"
        ANDROID_PLATFORM:     "${ANDROID_PLATFORM:-android-34}"
        ANDROID_BUILD_TOOLS:  "${ANDROID_BUILD_TOOLS:-34.0.0}"
        ANDROID_NDK_VERSION:  "${ANDROID_NDK_VERSION:-r26c}"

    image: ${IMAGE_NAME:-quickvulkanv1}:ubuntu-24.04
    container_name: ${CONTAINER_NAME:-quickvulkanv1-dev}

    environment:
      SSHD_ENABLED: "${SSHD_ENABLED:-true}"
      SSHD_PASSWORD_AUTH: "${SSHD_PASSWORD_AUTH:-false}"
      ROOT_PASSWORD: "${ROOT_PASSWORD:-CHANGE_ME_ROOT}"

      CREATE_USER: "${CREATE_USER:-true}"
      USER_NAME: "${USER_NAME:-developer}"
      USER_UID: "${USER_UID:-1000}"
      USER_GID: "${USER_GID:-1000}"
      USER_PASSWORD: "${USER_PASSWORD:-CHANGE_ME_USER}"
      USER_SUDO: "${USER_SUDO:-true}"
      TAKE_WORKSPACE: "${TAKE_WORKSPACE:-true}"

      CCACHE_DIR: "${CCACHE_DIR:-/opt/cache/ccache}"

      JAVA_HOME: "${JAVA_HOME:-/usr/lib/jvm/java-17-openjdk-amd64}"

    ports:
      - "${SSH_PORT:-7000}:22"
      - "${APP_PORTS:-7001-7010}:${APP_PORTS:-7001-7010}"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - "${WORKSPACE_PATH:-/mnt/data/dev-volumes/quickvulkanv1/workspace}:/workspace"
      - "${SSH_PATH:-/mnt/data/dev-volumes/quickvulkanv1/.ssh}:/root/.ssh"
      - "${HOME_PATH:-/mnt/data/dev-volumes/quickvulkanv1/home}:/home:rw"
      - "${CCACHE_PATH:-/mnt/data/dev-volumes/quickvulkanv1/ccache}:/opt/cache/ccache"

    # Choose ONE of the following runtime configs:
    # For NVIDIA host GPUs (requires nvidia-container-toolkit):
    # gpus: all
    # environment:
    #   NVIDIA_VISIBLE_DEVICES: all
    #   NVIDIA_DRIVER_CAPABILITIES: all

    # For Intel/AMD hosts (Mesa):
    # devices:
    #   - /dev/dri:/dev/dri
    # volumes:
    #   - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d:ro


    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped
